esphome:
    platform: ESP32
    board: esp32dev
    name: esp32-buzzer

logger: 
    level : NONE

output:
    - platform: ledc
      pin: 25
      id: buzzer

# Example usage in an automation
binary_sensor:
    - platform: gpio
      pin: 
        number: 13
        #inverted: true
      id: diffuseSensor
      on_press:
        then:
            - output.turn_on: buzzer      # Must be turned on before setting frequency & level
            - output.ledc.set_frequency: 
                id: buzzer
                frequency: "1000Hz"       # Frequency sets the wave size
            - output.set_level:
                id: buzzer
                level: "50%"              # level sets the %age time the PWM is on
      on_release:
        then:
            - output.turn_off: buzzer      