esphome:
    platform: ESP32
    board: esp32dev
    name: esp32-startstop-relay

logger:

switch:
    - platform: gpio
      pin: 16
      inverted: true
      id: relay1
    - platform: gpio
      pin: 17
      inverted: true
      id: relay2
      
binary_sensor:
    - platform: gpio
      pin: 
        number: 25
        mode: input_pullup
        inverted: true
      id: start
      on_press:
        then:
            - switch.turn_on: relay1
            - switch.turn_on: relay2
    - platform: gpio
      pin: 
        number: 26
        mode: input_pullup
        inverted: true
      id: stop
      on_press:
        then: 
            - switch.turn_off: relay1
            - switch.turn_off: relay2






