esphome:
  name: esp32-blink

esp32:
  board: esp32dev

wifi:
  ssid: "YOUR_WIFI_NAME"
  password: "YOUR_WIFI_PASSWORD"

# Serial monitor
logger:

# API communication
api:

# OTA
ota:
  - platform: esphome
    password: "MyStrongOTAPassword"

# GPIO output
output:
  - platform: gpio
    pin: GPIO2
    id: gLED

# Blink
interval:
  - interval: 500ms
    then:
      - output.turn_on: gLED

  - interval: 2s
    then:
      - output.turn_off: gLED