esphome:
    platform: ESP32
    board: esp32dev
    name: esp32-dht-lcd
    
logger:
    level: NONE 

# DHT11
sensor:
    - platform: dht
      pin: 25
      
      temperature:
        name: "Living Room Temperature"
        id: temp
      humidity:
        name: "Living Room humidity"
        id: humi
      update_interval: 2s
      model: DHT11

# Set pin I2C LCD 
i2c: 
    sda: 21
    scl: 22

# Configuration column & row      
display:
    - platform: lcd_pcf8574
      dimensions: 16x2
      address: 0x27
      lambda: |-
        it.printf(0,0, "Temp: %.1f°C", id(temp).state);
        it.printf(0,1, "Humi: %.1f%%", id(humi).state);